//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBon_API.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ibonTicketSoap")]
    public interface ibonTicketSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  jsonSting 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketData", ReplyAction="*")]
        iBon_API.ServiceReference1.GetTicketDataResponse GetTicketData(iBon_API.ServiceReference1.GetTicketDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketData", ReplyAction="*")]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.GetTicketDataResponse> GetTicketDataAsync(iBon_API.ServiceReference1.GetTicketDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  jsonSting 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTicketData", ReplyAction="*")]
        iBon_API.ServiceReference1.CheckTicketDataResponse CheckTicketData(iBon_API.ServiceReference1.CheckTicketDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTicketData", ReplyAction="*")]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.CheckTicketDataResponse> CheckTicketDataAsync(iBon_API.ServiceReference1.CheckTicketDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  CheckConnectionResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckConnection", ReplyAction="*")]
        iBon_API.ServiceReference1.CheckConnectionResponse CheckConnection(iBon_API.ServiceReference1.CheckConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.CheckConnectionResponse> CheckConnectionAsync(iBon_API.ServiceReference1.CheckConnectionRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  jsonSting 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketCount", ReplyAction="*")]
        iBon_API.ServiceReference1.GetTicketCountResponse GetTicketCount(iBon_API.ServiceReference1.GetTicketCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketCount", ReplyAction="*")]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.GetTicketCountResponse> GetTicketCountAsync(iBon_API.ServiceReference1.GetTicketCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketData", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.GetTicketDataRequestBody Body;
        
        public GetTicketDataRequest() {
        }
        
        public GetTicketDataRequest(iBon_API.ServiceReference1.GetTicketDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonSting;
        
        public GetTicketDataRequestBody() {
        }
        
        public GetTicketDataRequestBody(string jsonSting) {
            this.jsonSting = jsonSting;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.GetTicketDataResponseBody Body;
        
        public GetTicketDataResponse() {
        }
        
        public GetTicketDataResponse(iBon_API.ServiceReference1.GetTicketDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTicketDataResult;
        
        public GetTicketDataResponseBody() {
        }
        
        public GetTicketDataResponseBody(string GetTicketDataResult) {
            this.GetTicketDataResult = GetTicketDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTicketDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTicketData", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.CheckTicketDataRequestBody Body;
        
        public CheckTicketDataRequest() {
        }
        
        public CheckTicketDataRequest(iBon_API.ServiceReference1.CheckTicketDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTicketDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonSting;
        
        public CheckTicketDataRequestBody() {
        }
        
        public CheckTicketDataRequestBody(string jsonSting) {
            this.jsonSting = jsonSting;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTicketDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTicketDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.CheckTicketDataResponseBody Body;
        
        public CheckTicketDataResponse() {
        }
        
        public CheckTicketDataResponse(iBon_API.ServiceReference1.CheckTicketDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTicketDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckTicketDataResult;
        
        public CheckTicketDataResponseBody() {
        }
        
        public CheckTicketDataResponseBody(string CheckTicketDataResult) {
            this.CheckTicketDataResult = CheckTicketDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckConnection", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.CheckConnectionRequestBody Body;
        
        public CheckConnectionRequest() {
        }
        
        public CheckConnectionRequest(iBon_API.ServiceReference1.CheckConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckConnectionRequestBody {
        
        public CheckConnectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.CheckConnectionResponseBody Body;
        
        public CheckConnectionResponse() {
        }
        
        public CheckConnectionResponse(iBon_API.ServiceReference1.CheckConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckConnectionResult;
        
        public CheckConnectionResponseBody() {
        }
        
        public CheckConnectionResponseBody(string CheckConnectionResult) {
            this.CheckConnectionResult = CheckConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketCount", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.GetTicketCountRequestBody Body;
        
        public GetTicketCountRequest() {
        }
        
        public GetTicketCountRequest(iBon_API.ServiceReference1.GetTicketCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonSting;
        
        public GetTicketCountRequestBody() {
        }
        
        public GetTicketCountRequestBody(string jsonSting) {
            this.jsonSting = jsonSting;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBon_API.ServiceReference1.GetTicketCountResponseBody Body;
        
        public GetTicketCountResponse() {
        }
        
        public GetTicketCountResponse(iBon_API.ServiceReference1.GetTicketCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTicketCountResult;
        
        public GetTicketCountResponseBody() {
        }
        
        public GetTicketCountResponseBody(string GetTicketCountResult) {
            this.GetTicketCountResult = GetTicketCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ibonTicketSoapChannel : iBon_API.ServiceReference1.ibonTicketSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ibonTicketSoapClient : System.ServiceModel.ClientBase<iBon_API.ServiceReference1.ibonTicketSoap>, iBon_API.ServiceReference1.ibonTicketSoap {
        
        public ibonTicketSoapClient() {
        }
        
        public ibonTicketSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ibonTicketSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ibonTicketSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ibonTicketSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBon_API.ServiceReference1.GetTicketDataResponse iBon_API.ServiceReference1.ibonTicketSoap.GetTicketData(iBon_API.ServiceReference1.GetTicketDataRequest request) {
            return base.Channel.GetTicketData(request);
        }
        
        public string GetTicketData(string jsonSting) {
            iBon_API.ServiceReference1.GetTicketDataRequest inValue = new iBon_API.ServiceReference1.GetTicketDataRequest();
            inValue.Body = new iBon_API.ServiceReference1.GetTicketDataRequestBody();
            inValue.Body.jsonSting = jsonSting;
            iBon_API.ServiceReference1.GetTicketDataResponse retVal = ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).GetTicketData(inValue);
            return retVal.Body.GetTicketDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.GetTicketDataResponse> iBon_API.ServiceReference1.ibonTicketSoap.GetTicketDataAsync(iBon_API.ServiceReference1.GetTicketDataRequest request) {
            return base.Channel.GetTicketDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<iBon_API.ServiceReference1.GetTicketDataResponse> GetTicketDataAsync(string jsonSting) {
            iBon_API.ServiceReference1.GetTicketDataRequest inValue = new iBon_API.ServiceReference1.GetTicketDataRequest();
            inValue.Body = new iBon_API.ServiceReference1.GetTicketDataRequestBody();
            inValue.Body.jsonSting = jsonSting;
            return ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).GetTicketDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBon_API.ServiceReference1.CheckTicketDataResponse iBon_API.ServiceReference1.ibonTicketSoap.CheckTicketData(iBon_API.ServiceReference1.CheckTicketDataRequest request) {
            return base.Channel.CheckTicketData(request);
        }
        
        public string CheckTicketData(string jsonSting) {
            iBon_API.ServiceReference1.CheckTicketDataRequest inValue = new iBon_API.ServiceReference1.CheckTicketDataRequest();
            inValue.Body = new iBon_API.ServiceReference1.CheckTicketDataRequestBody();
            inValue.Body.jsonSting = jsonSting;
            iBon_API.ServiceReference1.CheckTicketDataResponse retVal = ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).CheckTicketData(inValue);
            return retVal.Body.CheckTicketDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.CheckTicketDataResponse> iBon_API.ServiceReference1.ibonTicketSoap.CheckTicketDataAsync(iBon_API.ServiceReference1.CheckTicketDataRequest request) {
            return base.Channel.CheckTicketDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<iBon_API.ServiceReference1.CheckTicketDataResponse> CheckTicketDataAsync(string jsonSting) {
            iBon_API.ServiceReference1.CheckTicketDataRequest inValue = new iBon_API.ServiceReference1.CheckTicketDataRequest();
            inValue.Body = new iBon_API.ServiceReference1.CheckTicketDataRequestBody();
            inValue.Body.jsonSting = jsonSting;
            return ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).CheckTicketDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBon_API.ServiceReference1.CheckConnectionResponse iBon_API.ServiceReference1.ibonTicketSoap.CheckConnection(iBon_API.ServiceReference1.CheckConnectionRequest request) {
            return base.Channel.CheckConnection(request);
        }
        
        public string CheckConnection() {
            iBon_API.ServiceReference1.CheckConnectionRequest inValue = new iBon_API.ServiceReference1.CheckConnectionRequest();
            inValue.Body = new iBon_API.ServiceReference1.CheckConnectionRequestBody();
            iBon_API.ServiceReference1.CheckConnectionResponse retVal = ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).CheckConnection(inValue);
            return retVal.Body.CheckConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.CheckConnectionResponse> iBon_API.ServiceReference1.ibonTicketSoap.CheckConnectionAsync(iBon_API.ServiceReference1.CheckConnectionRequest request) {
            return base.Channel.CheckConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<iBon_API.ServiceReference1.CheckConnectionResponse> CheckConnectionAsync() {
            iBon_API.ServiceReference1.CheckConnectionRequest inValue = new iBon_API.ServiceReference1.CheckConnectionRequest();
            inValue.Body = new iBon_API.ServiceReference1.CheckConnectionRequestBody();
            return ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).CheckConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBon_API.ServiceReference1.GetTicketCountResponse iBon_API.ServiceReference1.ibonTicketSoap.GetTicketCount(iBon_API.ServiceReference1.GetTicketCountRequest request) {
            return base.Channel.GetTicketCount(request);
        }
        
        public string GetTicketCount(string jsonSting) {
            iBon_API.ServiceReference1.GetTicketCountRequest inValue = new iBon_API.ServiceReference1.GetTicketCountRequest();
            inValue.Body = new iBon_API.ServiceReference1.GetTicketCountRequestBody();
            inValue.Body.jsonSting = jsonSting;
            iBon_API.ServiceReference1.GetTicketCountResponse retVal = ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).GetTicketCount(inValue);
            return retVal.Body.GetTicketCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iBon_API.ServiceReference1.GetTicketCountResponse> iBon_API.ServiceReference1.ibonTicketSoap.GetTicketCountAsync(iBon_API.ServiceReference1.GetTicketCountRequest request) {
            return base.Channel.GetTicketCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<iBon_API.ServiceReference1.GetTicketCountResponse> GetTicketCountAsync(string jsonSting) {
            iBon_API.ServiceReference1.GetTicketCountRequest inValue = new iBon_API.ServiceReference1.GetTicketCountRequest();
            inValue.Body = new iBon_API.ServiceReference1.GetTicketCountRequestBody();
            inValue.Body.jsonSting = jsonSting;
            return ((iBon_API.ServiceReference1.ibonTicketSoap)(this)).GetTicketCountAsync(inValue);
        }
    }
}
